language: python
os:
  - linux

python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - EXTRAS=base
  - EXTRAS=io
  - EXTRAS=web
  - EXTRAS=plot
  - EXTRAS=sphinx
  - EXTRAS=parallel
  - EXTRAS=all
  - EXTRAS=dev

addons:
  apt:
    packages:
      - graphviz

matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      env:
        - EXTRAS=all
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/Library/bin:$PATH"
      before_install:
        - choco install miniconda3
        - conda create --yes -n test python=3.7
        - source activate test
        - conda --version ; python --version ; pip --version
        - choco install graphviz.portable

    - os: windows
      language: sh
      python: "3.8"
      env:
        - EXTRAS=all
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/Library/bin:$PATH"
      before_install:
        - choco install miniconda3
        - conda create --yes -n test python=3.8
        - source activate test
        - conda --version ; python --version ; pip --version
        - choco install graphviz.portable

    - os: windows
      language: sh
      python: "3.9"
      env:
        - EXTRAS=all
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/Library/bin:$PATH"
      before_install:
        - choco install miniconda3
        - conda create --yes -n test python=3.9
        - source activate test
        - conda --version ; python --version ; pip --version
        - choco install graphviz.portable

# command to install dependencies
install:
  - pip install -r requirements/test.pip
  - if [[ $EXTRAS == 'base' ]]; then pip install -e .; fi
  - if [[ $EXTRAS != 'base' ]]; then pip install -e .[$EXTRAS]; fi

# command to run tests
script:
  - coverage run --source=schedula setup.py nosetests

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' && $EXTRAS == 'all' && $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi